### ISSUE TITLE
Project can not be compile in debug mode

### ISSUE THREAD

**Issue by amethyst-asuka** [xieguigang/VisualBasic_AppFramework#28]
Currently there is a solution can not be compile in debug mode:
https://github.com/xieguigang/VisualBasic_AppFramework/tree/master/DocumentFormats/VB_DataFrame

vbc compiler show a error code in the latest VisualStudio 2015 update 2:

Severity	Code	Description	Project	File	Line	Suppression State
Error		"vbc.exe" exited with code -2146232797.	+VB_Tabular.DataFrame

**Comment by xieguigang** [comment]
This is a bugs in the VisualStudio 2015 update 2 compiler of VisualBasic, and this bugs is already feedback on the Microsoft connect, wait for the bugs fixed solution from Microsoft.

**Comment by xieguigang** [comment]
https://connect.microsoft.com/VisualStudio/Feedback/Details/2693275

**Comment by xieguigang** [comment]
![bug](https://cloud.githubusercontent.com/assets/9410171/15289154/c55e62ec-1ba2-11e6-9daa-c2ac95e56fe8.png)

**Comment by xieguigang** [comment]
it seems that this problem fixed
